# -*- coding: utf-8 -*-
"""MajorProjectFusionModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uKp5KHTmAKooBvAsnmEcMFNx1hLcHSAq
"""

!unzip MGCD.zip -d /content/MGCD

!ls /content/MGCD

!ls -R /content/MGCD | head -n 50

BASE_PATH = "/content/MGCD/MGCD"
TRAIN_PATH = BASE_PATH + "/train"
TEST_PATH = BASE_PATH + "/test"

import os
import shutil

target_train = "/content/MGCD_binary/train"

os.makedirs(target_train + "/rain", exist_ok=True)
os.makedirs(target_train + "/no_rain", exist_ok=True)

for class_name in os.listdir(TRAIN_PATH):

    class_folder = os.path.join(TRAIN_PATH, class_name)

    if os.path.isdir(class_folder):

        if "6_cumulonimbus" in class_name.lower():
            dest = target_train + "/rain"
        else:
            dest = target_train + "/no_rain"

        for img in os.listdir(class_folder):
            if img.endswith(".jpg"):
                shutil.copy(os.path.join(class_folder, img), dest)

target_test = "/content/MGCD_binary/test"

os.makedirs(target_test + "/rain", exist_ok=True)
os.makedirs(target_test + "/no_rain", exist_ok=True)

for class_name in os.listdir(TEST_PATH):

    class_folder = os.path.join(TEST_PATH, class_name)

    if os.path.isdir(class_folder):

        if "6_cumulonimbus" in class_name.lower():
            dest = target_test + "/rain"
        else:
            dest = target_test + "/no_rain"

        for img in os.listdir(class_folder):
            if img.endswith(".jpg"):
                shutil.copy(os.path.join(class_folder, img), dest)

!ls /content/MGCD_binary/train

import pandas as pd

df = pd.read_excel("/content/MGCD/MGCD/train/6_cumulonimbus.xlsx")
df.head()

import os
import pandas as pd

BASE_PATH = "/content/MGCD/MGCD/train"

data_list = []

for class_name in os.listdir(BASE_PATH):

    class_folder = os.path.join(BASE_PATH, class_name)

    if os.path.isdir(class_folder):

        # Read corresponding Excel
        excel_path = os.path.join(BASE_PATH, class_name + ".xlsx")
        df = pd.read_excel(excel_path)

        # Determine binary label
        if "6_cumulonimbus" in class_name.lower():
            label = 1
        else:
            label = 0

        for _, row in df.iterrows():

            image_name = row["Name"] + ".jpg"
            image_path = os.path.join(class_folder, image_name)

            if os.path.exists(image_path):
                data_list.append([
                    image_path,
                    row["Temperature(℃)"],
                    row["Humidity(%RH)"],
                    row["Pressure(hpa)"],
                    row["Wind speed(m/s)"],
                    label
                ])

train_df = pd.DataFrame(data_list, columns=[
    "image_path", "temp", "humidity", "pressure", "wind", "label"
])

train_df.head()

train_df.shape

import os
import pandas as pd

BASE_PATH = "/content/MGCD/MGCD/test"

data_list = []

for class_name in os.listdir(BASE_PATH):

    class_folder = os.path.join(BASE_PATH, class_name)

    if os.path.isdir(class_folder):

        excel_path = os.path.join(BASE_PATH, class_name + ".xlsx")
        df = pd.read_excel(excel_path)

        if "6_cumulonimbus" in class_name.lower():
            label = 1
        else:
            label = 0

        for _, row in df.iterrows():

            image_name = row["Name"] + ".jpg"
            image_path = os.path.join(class_folder, image_name)

            if os.path.exists(image_path):
                data_list.append([
                    image_path,
                    row["Temperature(℃)"],
                    row["Humidity(%RH)"],
                    row["Pressure(hpa)"],
                    row["Wind speed(m/s)"],
                    label
                ])

test_df = pd.DataFrame(data_list, columns=[
    "image_path", "temp", "humidity", "pressure", "wind", "label"
])

test_df.head()

test_df.shape

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

train_df[["temp","humidity","pressure","wind"]] = scaler.fit_transform(
    train_df[["temp","humidity","pressure","wind"]]
)

test_df[["temp","humidity","pressure","wind"]] = scaler.transform(
    test_df[["temp","humidity","pressure","wind"]]
)

import tensorflow as tf

IMG_SIZE = 224
BATCH_SIZE = 32

def load_image(path):
    img = tf.io.read_file(path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, (IMG_SIZE, IMG_SIZE))
    img = img / 255.0
    return img

def create_dataset(df, batch_size=32, shuffle=True):

    image_paths = df["image_path"].values
    weather = df[["temp","humidity","pressure","wind"]].values
    labels = df["label"].values

    dataset = tf.data.Dataset.from_tensor_slices(
        (image_paths, weather, labels)
    )

    def process(image_path, weather_vec, label):
        image = load_image(image_path)
        weather_vec = tf.cast(weather_vec, tf.float32)
        label = tf.cast(tf.expand_dims(label, -1), tf.float32)
        return {"image_input": image,
                "weather_input": weather_vec}, label

    dataset = dataset.map(process, num_parallel_calls=tf.data.AUTOTUNE)

    if shuffle:
        dataset = dataset.shuffle(len(df))

    dataset = dataset.batch(batch_size).prefetch(tf.data.AUTOTUNE)

    return dataset

train_dataset = create_dataset(train_df, BATCH_SIZE, shuffle=True)
test_dataset  = create_dataset(test_df,  BATCH_SIZE, shuffle=False)

for _, y in train_dataset.take(5):
    print(tf.reduce_mean(y))

for batch in train_dataset.take(1):
    print(batch)

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Input, Dense, GlobalAveragePooling2D, Concatenate, Dropout
from tensorflow.keras.models import Model

IMG_SIZE = 224

# -----------------------
# Image Branch
# -----------------------
image_input = Input(shape=(IMG_SIZE, IMG_SIZE, 3), name="image_input")

base_model = MobileNetV2(
    include_top=False,
    weights="imagenet",
    input_tensor=image_input
)

base_model.trainable = False   # Phase 1 Freeze

x = GlobalAveragePooling2D()(base_model.output)
x = Dense(128, activation="relu")(x)
x = Dropout(0.3)(x)

# -----------------------
# Weather Branch
# -----------------------
weather_input = Input(shape=(4,), name="weather_input")

w = Dense(32, activation="relu")(weather_input)
w = Dense(16, activation="relu")(w)

# -----------------------
# Fusion
# -----------------------
fusion = Concatenate()([x, w])
fusion = Dense(64, activation="relu")(fusion)
fusion = Dropout(0.3)(fusion)

output = Dense(1, activation="sigmoid")(fusion)

model = Model(inputs=[image_input, weather_input], outputs=output)

model.summary()

import tensorflow as tf

def focal_loss(gamma=1.5, alpha=0.5):
    def loss(y_true, y_pred):
        bce = tf.keras.losses.binary_crossentropy(y_true, y_pred)
        p_t = y_true * y_pred + (1 - y_true) * (1 - y_pred)
        alpha_factor = y_true * alpha + (1 - y_true) * (1 - alpha)
        modulating_factor = tf.pow(1 - p_t, gamma)
        return alpha_factor * modulating_factor * bce
    return loss

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-4),
    loss=tf.keras.losses.BinaryCrossentropy(),
    metrics=[
        tf.keras.metrics.BinaryAccuracy(name="accuracy"),
        tf.keras.metrics.AUC(name="auc"),
        tf.keras.metrics.Recall(name="recall"),
        tf.keras.metrics.Precision(name="precision")
    ]
)

from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

early_stop = EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

lr_scheduler = ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.2,
    patience=3,
    min_lr=1e-6
)

train_df["label"].value_counts()

test_df['label'].value_counts()

history1 = model.fit(
    train_dataset,
    validation_data=test_dataset,
    epochs=10,
    callbacks=[early_stop, lr_scheduler]
)

model.save("mgcd_multimodal_mobilenet_phase1.keras")

from google.colab import files
files.download("mgcd_multimodal_mobilenet_phase1.keras")

!ls -lh

base_model.trainable = True

for layer in base_model.layers[:-30]:
    layer.trainable = False

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-5),
    loss=tf.keras.losses.BinaryCrossentropy(),
    metrics=[
        tf.keras.metrics.BinaryAccuracy(name="accuracy"),
        tf.keras.metrics.AUC(name="auc"),
        tf.keras.metrics.Recall(name="recall"),
        tf.keras.metrics.Precision(name="precision")
    ]
)

history2 = model.fit(
    train_dataset,
    validation_data=test_dataset,
    epochs=5,
    callbacks=[early_stop, lr_scheduler]
)

model.evaluate(test_dataset)

import numpy as np
from sklearn.metrics import confusion_matrix, classification_report

# Get predictions in one go
y_true = []
y_pred = []

for x, y in test_dataset:
    predictions = model.predict(x, verbose=0)
    y_true.extend(y.numpy().flatten())
    y_pred.extend((predictions.flatten() > 0.5).astype(int))

# Convert to numpy
y_true = np.array(y_true)
y_pred = np.array(y_pred)

print("Confusion Matrix:")
print(confusion_matrix(y_true, y_pred))

print("\nClassification Report:")
print(classification_report(y_true, y_pred, digits=4))

import pandas as pd

history_df = pd.DataFrame(history2.history)
history_df.to_csv("history2_phase2.csv", index=False)

from google.colab import files
files.download("history2_phase2.csv")

model.save("mgcd_final_multimodal.keras")

from google.colab import files
files.download("mgcd_final_multimodal.keras")

import pandas as pd

pd.DataFrame(history2.history).to_csv("history_finetune.csv", index=False)
files.download("history_finetune.csv")



IMAGE-ONLY MODEL

import tensorflow as tf
import numpy as np
import pandas as pd
import random

seed = 42
tf.random.set_seed(seed)
np.random.seed(seed)
random.seed(seed)

tf.keras.backend.clear_session()

def create_image_only_dataset(df, batch_size=32, shuffle=True):

    image_paths = df["image_path"].values
    labels = df["label"].values

    dataset = tf.data.Dataset.from_tensor_slices((image_paths, labels))

    def process(image_path, label):
        image = load_image(image_path)
        label = tf.cast(label, tf.float32)
        return image, label

    dataset = dataset.map(process, num_parallel_calls=tf.data.AUTOTUNE)

    if shuffle:
        dataset = dataset.shuffle(1000)

    dataset = dataset.batch(batch_size).prefetch(tf.data.AUTOTUNE)

    return dataset


train_image_dataset = create_image_only_dataset(train_df)
test_image_dataset  = create_image_only_dataset(test_df, shuffle=False)

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Input, Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.models import Model

tf.keras.backend.clear_session()

IMG_SIZE = 224

image_input = Input(shape=(IMG_SIZE, IMG_SIZE, 3))

base_model = MobileNetV2(
    include_top=False,
    weights="imagenet",
    input_tensor=image_input
)

base_model.trainable = False

x = GlobalAveragePooling2D()(base_model.output)
x = Dense(128, activation="relu")(x)
x = Dropout(0.3)(x)

output = Dense(1, activation="sigmoid")(x)

image_model = Model(inputs=image_input, outputs=output)

image_model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-4),
    loss="binary_crossentropy",
    metrics=[
        tf.keras.metrics.BinaryAccuracy(name="accuracy"),
        tf.keras.metrics.AUC(name="auc"),
        tf.keras.metrics.Recall(name="recall"),
        tf.keras.metrics.Precision(name="precision")
    ]
)

early_stop = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    patience=3,
    restore_best_weights=True
)

history_img_phase1 = image_model.fit(
    train_image_dataset,
    validation_data=test_image_dataset,
    epochs=8,
    callbacks=[early_stop]
)

image_model.evaluate(test_image_dataset)

images_all = []
labels_all = []

for (x, y) in test_dataset:
    images_all.append(x["image_input"])
    labels_all.append(y)

images_all = tf.concat(images_all, axis=0)
labels_all = tf.concat(labels_all, axis=0)

preds = image_model.predict(images_all)

y_true = labels_all.numpy().flatten()
y_pred = (preds.flatten() > 0.5).astype(int)

from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_true, y_pred))
print(classification_report(y_true, y_pred))

image_model.save("image_only_model.keras")

from google.colab import files
files.download("image_only_model.keras")



WEATHER-ONLY MODEL

def create_weather_only_dataset(df, batch_size=32, shuffle=True):

    weather = df[["temp","humidity","pressure","wind"]].values
    labels = df["label"].values

    dataset = tf.data.Dataset.from_tensor_slices((weather, labels))

    def process(weather_vec, label):
        weather_vec = tf.cast(weather_vec, tf.float32)
        label = tf.cast(label, tf.float32)
        return weather_vec, label

    dataset = dataset.map(process)

    if shuffle:
        dataset = dataset.shuffle(1000)

    dataset = dataset.batch(batch_size).prefetch(tf.data.AUTOTUNE)

    return dataset


train_weather_dataset = create_weather_only_dataset(train_df)
test_weather_dataset  = create_weather_only_dataset(test_df, shuffle=False)

from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

tf.keras.backend.clear_session()

weather_model = Sequential([
    Dense(32, activation="relu", input_shape=(4,)),
    Dense(16, activation="relu"),
    Dense(1, activation="sigmoid")
])

from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

tf.keras.backend.clear_session()

weather_model = Sequential([
    Dense(32, activation="relu", input_shape=(4,)),
    Dense(16, activation="relu"),
    Dense(1, activation="sigmoid")
])

weather_model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-3),
    loss="binary_crossentropy",
    metrics=[
        tf.keras.metrics.BinaryAccuracy(name="accuracy"),
        tf.keras.metrics.AUC(name="auc"),
        tf.keras.metrics.Recall(name="recall"),
        tf.keras.metrics.Precision(name="precision")
    ]
)

early_stop = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    patience=3,
    restore_best_weights=True
)

history_weather = weather_model.fit(
    train_weather_dataset,
    validation_data=test_weather_dataset,
    epochs=20,
    callbacks=[early_stop]
)

weather_model.evaluate(test_weather_dataset)

weather_all = []
labels_all = []

for (x, y) in test_dataset:
    weather_all.append(x["weather_input"])
    labels_all.append(y)

weather_all = tf.concat(weather_all, axis=0)
labels_all = tf.concat(labels_all, axis=0)

preds = weather_model.predict(weather_all)

y_true = labels_all.numpy().flatten()
y_pred = (preds.flatten() > 0.5).astype(int)

print(confusion_matrix(y_true, y_pred))
print(classification_report(y_true, y_pred))

weather_model.save("weather_only_model.keras")

from google.colab import files
files.download("weather_only_model.keras")



import pandas as pd

comparison = pd.DataFrame({
    "Model": ["Weather-Only", "Image-Only", "Fusion"],
    "Accuracy": [0.8225, 0.9105, 0.9330],
    "AUC": [0.8167, 0.9508, 0.9464],
    "Recall (Rain)": [0.6644, 0.7530, 0.7376],
    "Precision (Rain)": [0.4319, 0.6748, 0.7916]
})

comparison.sort_values(by="Accuracy", ascending=False)



from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np

# Collect full test data once
images_all = []
weather_all = []
labels_all = []

for (x, y) in test_dataset:
    images_all.append(x["image_input"])
    weather_all.append(x["weather_input"])
    labels_all.append(y)

images_all = tf.concat(images_all, axis=0)
weather_all = tf.concat(weather_all, axis=0)
labels_all = tf.concat(labels_all, axis=0).numpy().flatten()

# Predictions
fusion_preds  = model.predict({"image_input": images_all, "weather_input": weather_all}).flatten()
image_preds   = image_model.predict(images_all).flatten()
weather_preds = weather_model.predict(weather_all).flatten()

# ROC
plt.figure(figsize=(7,6))

for preds, name in [
    (fusion_preds, "Fusion"),
    (image_preds, "Image-Only"),
    (weather_preds, "Weather-Only")
]:
    fpr, tpr, _ = roc_curve(labels_all, preds)
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{name} (AUC={roc_auc:.2f})")

plt.plot([0,1],[0,1],'--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison")
plt.legend()
plt.show()

import pandas as pd

comparison = pd.DataFrame({
    "Model": ["Weather-Only", "Image-Only", "Fusion"],
    "Accuracy": [0.8225, 0.9105, 0.9330],
    "Recall": [0.6644, 0.7530, 0.7376],
    "Precision": [0.4319, 0.6748, 0.7916]
})

comparison.set_index("Model").plot(kind="bar", figsize=(8,5))
plt.title("Model Performance Comparison")
plt.ylim(0,1)
plt.xticks(rotation=0)
plt.show()